pipeline:
  name: Build juiceshop15.3.0
  identifier: Build_AfikApprisk_juiceshop15_3_0_1736419541445
  projectIdentifier: my_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Snyk
                  name: Snyk_1
                  identifier: Snyk_1
                  spec:
                    mode: orchestration
                    config: oss
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: none
                    privileged: true
                    auth:
                      access_token: aa998017-544c-433a-bd8c-3901ce58d453
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1736418776738
        repoName: AfikApprisk/juiceshop15.3.0
        build: <+input>
