pipeline:
  name: Build juiceshop15.3.0
  identifier: Build_AfikApprisk_juiceshop15_3_0_1736419541445
  projectIdentifier: my_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      # Install and Authenticate to Snyk
                         npm install -g snyk
                         npm install
                         snyk auth  
                         # Snyk test
                         snyk test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1736418776738
        repoName: AfikApprisk/juiceshop15.3.0
        build: <+input>
